// Generated by generate-ags-theme.py from colors-universal.json
// Palette: custom_dotfiles
// Variant: dark

export const AGS_THEME = {
  // Base colors
  bg: '#1e1e2e',
  bgAlt: '#282a36',
  bgElevated: '#333544',
  bgOverlay: '#3e3e4e',
  fg: '#f8f8f2',
  fgMuted: '#a0a0b0',
  fgSubtle: '#6272a4',
  border: '#44475a',
  borderFocus: '#f8f8f2',
  borderSubtle: '#3a3a4a',

  // ANSI 16-color palette
  black: '#262626',
  red: '#E64747',
  green: '#42E66C',
  yellow: '#E4F34A',
  blue: '#9B6BDF',
  magenta: '#E356A7',
  cyan: '#75D7EC',
  orange: '#EFA554',
  brightBlack: '#7A7A7A',
  brightRed: '#FF5555',
  brightGreen: '#50FA7B',
  brightYellow: '#F1FA8C',
  brightBlue: '#BD93F9',
  brightMagenta: '#ff79c6',
  brightCyan: '#8BE9FD',
  brightWhite: '#FFB86C',

  // Semantic colors
  primary: {
    main: '#9B6BDF',
    light: '#BD93F9',
    dark: '#7a4fc7',
    on: '#1e1e2e',
  },
  secondary: {
    main: '#75D7EC',
    light: '#8BE9FD',
    dark: '#5ab8c9',
    on: '#1e1e2e',
  },
  accent: {
    main: '#EFA554',
    light: '#FFB86C',
    dark: '#c4823d',
    on: '#1e1e2e',
  },
  error: {
    main: '#E64747',
    light: '#FF5555',
    dark: '#b83838',
    on: '#f8f8f2',
  },
  warning: {
    main: '#E4F34A',
    light: '#F1FA8C',
    dark: '#b8c23a',
    on: '#1e1e2e',
  },
  success: {
    main: '#42E66C',
    light: '#50FA7B',
    dark: '#35b855',
    on: '#1e1e2e',
  },
  info: {
    main: '#75D7EC',
    light: '#8BE9FD',
    dark: '#5ab8c9',
    on: '#1e1e2e',
  },

  // State colors
  state: {
    hover: {
      bg: '#3e3e4e',
    },
    active: {
      bg: '#4a4a5a',
    },
    focus: {
      bg: '#505060',
      ring: '#f8f8f2',
    },
    disabled: {
      fg: '#6272a4',
      bg: '#2a2a3a',
    },
    selected: {
      bg: '#9B6BDF',
    },
  },

  // Alpha values
  alpha: {
    bg: 0.93,
    surface: 0.95,
    overlay: 0.98,
    border: 1.0,
    shadow: 0.93,
  },

  // Typography
  typography: {
    font_family: 'CaskaydiaMono Nerd Font',
    font_size: 10,
    monospace_family: 'CaskaydiaMono Nerd Font Mono',
    monospace_size: 10,
  },

  // Spacing
  spacing: {
    base: 4,
    gap: 10,
    radius: 10,
    border_width: 2,
  },

  // Hyprland values (synced at runtime from hyprctl)
  hyprland: {
    activeOpacity: 0.9,
    inactiveOpacity: 0.9,
    rounding: 10,
    borderSize: 2,
    gapsOut: 10,
    activeBorder: '0xF8F8F2',
    inactiveBorder: '0x7A7A7A',
  },

  // Metadata
  name: 'custom_dotfiles',
  variant: 'dark',
};

// CSS variable generators
export function toDefineColor(name, value) {
  return `@define-color ${name} ${value};`;
}

export function alpha(color, a) {
  return `alpha(${color}, ${a})`;
}

export function rgba(color, a) {
  // Convert hex to rgba
  const hex = color.replace('#', '');
  const r = parseInt(hex.slice(0, 2), 16);
  const g = parseInt(hex.slice(2, 4), 16);
  const b = parseInt(hex.slice(4, 6), 16);
  return `rgba(${r}, ${g}, ${b}, ${a})`;
}